# Site wide configuration

title: Head in the Clouds
locale: en_US
logo: # no logo

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Head in the Clouds
  avatar: Cloud_Ace_Final.png
  bio: "with Kenneth G. Hartman<p>Certified SANS Instructor"
  email: kgh@kennethghartman.com
  # Do not include the @ symbol in your Twitter username
  twitter: kennethghartman
  linkedin: #kennethghartman
  github: Resistor52
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics: UA-25220220-1
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
#highlight-color: '#CC0000'
highlight-color: '#ff8800'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  episodes:
    output: true
collections_dir: docs
base_url: "/blog"
url: "https://rodrigopace.github.io/"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: jekyll-theme-midnight

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%y-%b-%d'
